### PR TITLE
Add Discord chat link

### PR DESCRIPTION
**Pull request by ryyppy**
image

I currently put it in the header, would be cool to have a discord logo or such in a visible way!

Related to #48

### CODE REVIEW

**Comment by okonet** [comment]
I’d put it into footer for now since this is rather misleading (it will navigate away from the website). I can create a special kind of navigation for such things on top later

**Comment by nikgraf** [comment]
screen shot 2018-10-31 at 05 42 41

@okonet just tried to put it into social links. Looks ugly, because the lib we use doesn't seem to have a Discord icon.

**Comment by okonet** [comment]
Bummer. Probably a good PR for a lib then?

**Comment by nikgraf** [comment]
@okonet totally, but with my skills this could take a while. Don't have that time today :(

**Pull request merged**
