### PR TITLE
Speakers page

### PR DESCRIPTION
**Pull request by okonet**
This PR

1. Fixes and improves layout and markup of the `/speakers` page: 2019-01-30 at 17 10

1. Updates main navigation layout and position so it doesn't hangs in the air on the home page: 
2019-01-30 at 17 11

1. Fixes "full" grid layout not taking all the space on mobile devices: 2019-01-30 at 17 10

### CODE REVIEW

**Comment by okonet** [comment]
We should update the data before we merge I’d say

**Comment by okonet** [comment]
Alternatively I could split the PR with improvement and the page into 2 if you think it’s going to take too long to add initial data. My hope was that you could just start adding workshop leaders and we would publish it. I’d need it to add them to the home page anyways.

**Comment by nikgraf** [comment]
@okonet I'm pro taking out the speaker tab and merging this

**Comment by okonet** [comment]
Updated and LGTM

**Pull request merged**
