### PR TITLE
Sponsors page design

### PR DESCRIPTION
**Pull request by okonet**
2018-10-02 at 10 54

### CODE REVIEW

**Comment by ryyppy** [comment]
I like the cards, but I don't like the visual separation from the main content

**Comment by okonet** [comment]
@nikgraf what about you? I think it's really stands out now but if both you and @ryyppy don't like I'll put it back into the page content.

**Comment by nikgraf** [comment]
Is there a preview page? Based on this screenshot it looks good to me, but hard to judge out of context.

**Comment by okonet** [comment]
@nikgraf yes, click on Netlify check

**Pull request merged**
