### PR TITLE
Speakers & Schedule

### PR DESCRIPTION
**Pull request by nikgraf**

### CODE REVIEW

**Comment by okonet** [comment]
LGTM. I’m going to fix the mobile layout in another pr

**Comment by okonet** [comment]
Another question: did you optimize images with ImageOptim? Otherwise I can do this.

**Comment by nikgraf** [comment]
@okonet nope, didn't do that. would be awesome if you can do the image optimzations

**Comment by okonet** [comment]
Okay I’ll do that

**Comment by okonet** [comment]
@nikgraf check it out

**Comment by nikgraf** [comment]
sweet, thx @okonet 

let's 🚢 it!

**Pull request merged**
